<a href="https://colab.research.google.com/github/AndresMendoza30/repositorio1/blob/EXAMEN-07-%2F06-%2F2024/Examen_ii.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --target=$nb_path nacal
from nacal import *

1. Para la siguiente matriz $$\left[ \begin{array}{cccc}3&-2&2&1\\1&-1&-1&-3\\2&1&2&4\\4&-4&1&2\\ \end{array} \right]$$ lleva a cabo el algoritmo de eliminación paso a paso.

Escribe en una celda separada cada operacion elemental.

In [1]:
import numpy as np

# Definir la matriz inicial
A = np.array([[3, -2, 2, 1],
              [1, -1, -1, -3],
              [2, 1, 2, 4],
              [4, -4, 1, 2]], dtype=float)

print("Matriz inicial:\n", A)

# Paso 1: Hacer el pivote de la primera columna igual a 1
A[0] = A[0] / A[0, 0]
print("\nPaso 1:\n", A)

# Paso 2: Hacer ceros debajo del pivote en la primera columna
A[1] = A[1] - A[0] * A[1, 0]
A[2] = A[2] - A[0] * A[2, 0]
A[3] = A[3] - A[0] * A[3, 0]
print("\nPaso 2:\n", A)

# Paso 3: Hacer el pivote de la segunda columna igual a 1
A[1] = A[1] / A[1, 1]
print("\nPaso 3:\n", A)

# Paso 4: Hacer ceros debajo del pivote en la segunda columna
A[2] = A[2] - A[1] * A[2, 1]
A[3] = A[3] - A[1] * A[3, 1]
print("\nPaso 4:\n", A)


A[2] = A[2] / A[2, 2]
print("\nPaso 5:\n", A)


A[3] = A[3] - A[2] * A[3, 2]
print("\nPaso 6:\n", A)


A[3] = A[3] / A[3, 3]
print("\nPaso 7:\n", A)


A[2] = A[2] - A[3] * A[2, 3]
A[1] = A[1] - A[3] * A[1, 3]
A[0] = A[0] - A[3] * A[0, 3]
print("\nPaso 8:\n", A)


A[1] = A[1] - A[2] * A[1, 2]
A[0] = A[0] - A[2] * A[0, 2]
print("\nPaso 9:\n", A)


A[0] = A[0] - A[1] * A[0, 1]
print("\nPaso 10:\n", A)

print("\nMatriz en forma escalonada reducida:\n", A)


Matriz inicial:
 [[ 3. -2.  2.  1.]
 [ 1. -1. -1. -3.]
 [ 2.  1.  2.  4.]
 [ 4. -4.  1.  2.]]

Paso 1:
 [[ 1.         -0.66666667  0.66666667  0.33333333]
 [ 1.         -1.         -1.         -3.        ]
 [ 2.          1.          2.          4.        ]
 [ 4.         -4.          1.          2.        ]]

Paso 2:
 [[ 1.         -0.66666667  0.66666667  0.33333333]
 [ 0.         -0.33333333 -1.66666667 -3.33333333]
 [ 0.          2.33333333  0.66666667  3.33333333]
 [ 0.         -1.33333333 -1.66666667  0.66666667]]

Paso 3:
 [[ 1.         -0.66666667  0.66666667  0.33333333]
 [-0.          1.          5.         10.        ]
 [ 0.          2.33333333  0.66666667  3.33333333]
 [ 0.         -1.33333333 -1.66666667  0.66666667]]

Paso 4:
 [[  1.          -0.66666667   0.66666667   0.33333333]
 [ -0.           1.           5.          10.        ]
 [  0.           0.         -11.         -20.        ]
 [  0.           0.           5.          14.        ]]

Paso 5:
 [[ 1.         -0.666

2. Escriba las siguientes matrices elementales de orden 4.


(a) I τ
[(−7)1+3]

(b) I τ
[(1)1+4]

(c) I τ
[(3)2+1]

(d) I τ
[(−10)3]

In [3]:
import numpy as np

def elemental_matrix(operation, n=4):

    E = np.eye(n)
    scalar, src, tgt = operation
    if tgt is not None:
        E[tgt] += scalar * E[src]
    else:
        E[src] *= scalar
    return E


operations = [
    (-7, 0, 2),    # (a) I τ [(-7)R1 + R3]
    (1, 0, 3),     # (b) I τ [R1 + R4]
    (3, 1, 0),     # (c) I τ [(3)R2 + R1]
    (-10, 2, None) # (d) I τ [(-10)R3]
]


for i, op in enumerate(operations, start=1):
    E = elemental_matrix(op)
    print(f"Matriz elemental (parte {chr(96 + i)}):\n{E}\n")



Matriz elemental (parte a):
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [-7.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

Matriz elemental (parte b):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 1.]]

Matriz elemental (parte c):
[[1. 3. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Matriz elemental (parte d):
[[  1.   0.   0.   0.]
 [  0.   1.   0.   0.]
 [ -0.  -0. -10.  -0.]
 [  0.   0.   0.   1.]]



3. Sea la matriz A = $\left[ \begin{array}{cccc}1&1&1&1\\0&1&1&1\\1&2&3&4\\4&-4&1&2\\ \end{array} \right]$
, exprese las siguientes transformaciones elementales de

A como productos de A por matrices elementales y escriba el resultado:

(a) Multiplicar la primera columna por 3. (b) Restar la primera columna de la segunda.

In [4]:
import numpy as np


A = np.array([
    [1, 1, 1, 1],
    [0, 1, 1, 1],
    [1, 2, 3, 4],
    [4, -4, 1, 2]
], dtype=float)

print("Matriz A inicial:\n", A)

# (a) Multiplicar la primera columna por 3
# La matriz elemental para multiplicar la primera columna por 3
E1 = np.eye(4)
E1[:, 0] *= 3

# Resultado de la transformación (a)
A_a = np.dot(E1, A)
print("\n(a) Multiplicar la primera columna por 3:\n", A_a)

# (b) Restar la primera columna de la segunda
# La matriz elemental para restar la primera columna de la segunda
E2 = np.eye(4)
E2[1, 0] = -1

# Resultado de la transformación (b)
A_b = np.dot(A, E2)
print("\n(b) Restar la primera columna de la segunda:\n", A_b)


Matriz A inicial:
 [[ 1.  1.  1.  1.]
 [ 0.  1.  1.  1.]
 [ 1.  2.  3.  4.]
 [ 4. -4.  1.  2.]]

(a) Multiplicar la primera columna por 3:
 [[ 3.  3.  3.  3.]
 [ 0.  1.  1.  1.]
 [ 1.  2.  3.  4.]
 [ 4. -4.  1.  2.]]

(b) Restar la primera columna de la segunda:
 [[ 0.  1.  1.  1.]
 [-1.  1.  1.  1.]
 [-1.  2.  3.  4.]
 [ 8. -4.  1.  2.]]


4. Realiza el algoritmo de eliminación de Gauss-Jordan para la matriz del ejercicio 1, es decir continua las modificaciones de la matriz mediante operaciones elementales.
Por cada paso del algoritmo escribe la celda de código correspondiente.

In [5]:
import numpy as np

A = np.array([[3, -2, 2, 1],
              [1, -1, -1, -3],
              [2, 1, 2, 4],
              [4, -4, 1, 2]], dtype=float)

print("Matriz inicial:\n", A)


A[0] = A[0] / A[0, 0]
print("\nPaso 1:\n", A)


A[1] = A[1] - A[0] * A[1, 0]
A[2] = A[2] - A[0] * A[2, 0]
A[3] = A[3] - A[0] * A[3, 0]
print("\nPaso 2:\n", A)


A[1] = A[1] / A[1, 1]
print("\nPaso 3:\n", A)


A[2] = A[2] - A[1] * A[2, 1]
A[3] = A[3] - A[1] * A[3, 1]
print("\nPaso 4:\n", A)


A[2] = A[2] / A[2, 2]
print("\nPaso 5:\n", A)


A[3] = A[3] - A[2] * A[3, 2]
print("\nPaso 6:\n", A)


A[3] = A[3] / A[3, 3]
print("\nPaso 7:\n", A)


A[2] = A[2] - A[3] * A[2, 3]
A[1] = A[1] - A[3] * A[1, 3]
A[0] = A[0] - A[3] * A[0, 3]
print("\nPaso 8:\n", A)


A[1] = A[1] - A[2] * A[1, 2]
A[0] = A[0] - A[2] * A[0, 2]
print("\nPaso 9:\n", A)


A[0] = A[0] - A[1] * A[0, 1]
print("\nPaso 10:\n", A)

print("\nMatriz en forma escalonada reducida:\n", A)

Matriz inicial:
 [[ 3. -2.  2.  1.]
 [ 1. -1. -1. -3.]
 [ 2.  1.  2.  4.]
 [ 4. -4.  1.  2.]]

Paso 1:
 [[ 1.         -0.66666667  0.66666667  0.33333333]
 [ 1.         -1.         -1.         -3.        ]
 [ 2.          1.          2.          4.        ]
 [ 4.         -4.          1.          2.        ]]

Paso 2:
 [[ 1.         -0.66666667  0.66666667  0.33333333]
 [ 0.         -0.33333333 -1.66666667 -3.33333333]
 [ 0.          2.33333333  0.66666667  3.33333333]
 [ 0.         -1.33333333 -1.66666667  0.66666667]]

Paso 3:
 [[ 1.         -0.66666667  0.66666667  0.33333333]
 [-0.          1.          5.         10.        ]
 [ 0.          2.33333333  0.66666667  3.33333333]
 [ 0.         -1.33333333 -1.66666667  0.66666667]]

Paso 4:
 [[  1.          -0.66666667   0.66666667   0.33333333]
 [ -0.           1.           5.          10.        ]
 [  0.           0.         -11.         -20.        ]
 [  0.           0.           5.          14.        ]]

Paso 5:
 [[ 1.         -0.666

5. Compara tus resultados del ejercicio 1 con el metodo Elim()

In [6]:
import numpy as np
from scipy.linalg import lu

# Definir la matriz inicial
A = np.array([
    [3, -2, 2, 1],
    [1, -1, -1, -3],
    [2, 1, 2, 4],
    [4, -4, 1, 2]
], dtype=float)

print("Matriz A inicial:\n", A)


A[0] = A[0] / A[0, 0]
print("\nPaso 1:\n", A)


A[1] = A[1] - A[0] * A[1, 0]
A[2] = A[2] - A[0] * A[2, 0]
A[3] = A[3] - A[0] * A[3, 0]
print("\nPaso 2:\n", A)

A[1] = A[1] / A[1, 1]
print("\nPaso 3:\n", A)

A[2] = A[2] - A[1] * A[2, 1]
A[3] = A[3] - A[1] * A[3, 1]
print("\nPaso 4:\n", A)

A[2] = A[2] / A[2, 2]
print("\nPaso 5:\n", A)

A[3] = A[3] - A[2] * A[3, 2]
print("\nPaso 6:\n", A)

A[3] = A[3] / A[3, 3]
print("\nPaso 7:\n", A)

A[2] = A[2] - A[3] * A[2, 3]
A[1] = A[1] - A[3] * A[1, 3]
A[0] = A[0] - A[3] * A[0, 3]
print("\nPaso 8:\n", A)

A[1] = A[1] - A[2] * A[1, 2]
A[0] = A[0] - A[2] * A[0, 2]
print("\nPaso 9:\n", A)

A[0] = A[0] - A[1] * A[0, 1]
print("\nPaso 10:\n", A)

print("\nMatriz en forma escalonada reducida:\n", A)

P, L, U = lu(A)

print("\nMatriz P:\n", P)
print("\nMatriz L:\n", L)
print("\nMatriz U:\n", U)


Matriz A inicial:
 [[ 3. -2.  2.  1.]
 [ 1. -1. -1. -3.]
 [ 2.  1.  2.  4.]
 [ 4. -4.  1.  2.]]

Paso 1:
 [[ 1.         -0.66666667  0.66666667  0.33333333]
 [ 1.         -1.         -1.         -3.        ]
 [ 2.          1.          2.          4.        ]
 [ 4.         -4.          1.          2.        ]]

Paso 2:
 [[ 1.         -0.66666667  0.66666667  0.33333333]
 [ 0.         -0.33333333 -1.66666667 -3.33333333]
 [ 0.          2.33333333  0.66666667  3.33333333]
 [ 0.         -1.33333333 -1.66666667  0.66666667]]

Paso 3:
 [[ 1.         -0.66666667  0.66666667  0.33333333]
 [-0.          1.          5.         10.        ]
 [ 0.          2.33333333  0.66666667  3.33333333]
 [ 0.         -1.33333333 -1.66666667  0.66666667]]

Paso 4:
 [[  1.          -0.66666667   0.66666667   0.33333333]
 [ -0.           1.           5.          10.        ]
 [  0.           0.         -11.         -20.        ]
 [  0.           0.           5.          14.        ]]

Paso 5:
 [[ 1.         -0.6

 6. Compara tus resultados del ejercicio 4 con el metodo ElimGJ()

In [9]:
import numpy as np

# Definir la matriz inicial
A = np.array([
    [3, -2, 2, 1],
    [1, -1, -1, -3],
    [2, 1, 2, 4],
    [4, -4, 1, 2]
], dtype=float)

print("Matriz A inicial:\n", A)

# Paso 1: Hacer el pivote de la primera fila igual a 1
A[0] = A[0] / A[0, 0]
print("\nPaso 1:\n", A)

# Paso 2: Hacer ceros en la primera columna para todas las filas excepto la primera
A[1] = A[1] - A[0] * A[1, 0]
A[2] = A[2] - A[0] * A[2, 0]
A[3] = A[3] - A[0] * A[3, 0]
print("\nPaso 2:\n", A)

# Paso 3: Hacer el pivote de la segunda fila igual a 1
A[1] = A[1] / A[1, 1]
print("\nPaso 3:\n", A)

# Paso 4: Hacer ceros en la segunda columna para todas las filas excepto la segunda
A[0] = A[0] - A[1] * A[0, 1]
A[2] = A[2] - A[1] * A[2, 1]
A[3] = A[3] - A[1] * A[3, 1]
print("\nPaso 4:\n", A)

# Paso 5: Hacer el pivote de la tercera fila igual a 1
A[2] = A[2] / A[2, 2]
print("\nPaso 5:\n", A)

# Paso 6: Hacer ceros en la tercera columna para todas las filas excepto la tercera
A[0] = A[0] - A[2] * A[0, 2]
A[1] = A[1] - A[2] * A[1, 2]
A[3] = A[3] - A[2] * A[3, 2]
print("\nPaso 6:\n", A)

# Paso 7: Hacer el pivote de la cuarta fila igual a 1
A[3] = A[3] / A[3, 3]
print("\nPaso 7:\n", A)

# Paso 8: Hacer ceros en la cuarta columna para todas las filas excepto la cuarta
A[0] = A[0] - A[3] * A[0, 3]
A[1] = A[1] - A[3] * A[1, 3]
A[2] = A[2] - A[3] * A[2, 3]
print("\nPaso 8:\n", A)

print("\nMatriz en forma escalonada reducida:\n", A)

def gauss_jordan(A):
    """
    Realiza el algoritmo de eliminación Gauss-Jordan sobre la matriz A.

    Parámetros:
    A (numpy.ndarray): Matriz sobre la cual se realizará la eliminación Gauss-Jordan.

    Retorna:
    numpy.ndarray: La matriz en forma escalonada reducida.
    """
    m, n = A.shape
    for i in range(min(m, n)):
        # Hacer el pivote igual a 1
        A[i] = A[i] / A[i, i]
        # Hacer ceros en la columna del pivote
        for j in range(m):
            if i != j:
                A[j] = A[j] - A[i] * A[j, i]
    return A

# Reiniciar la matriz A a su valor inicial
A = np.array([
    [3, -2, 2, 1],
    [1, -1, -1, -3],
    [2, 1, 2, 4],
    [4, -4, 1, 2]
], dtype=float)

# Aplicar el método de eliminación Gauss-Jordan
A_gj = gauss_jordan(A.copy())
print("\nMatriz en forma escalonada reducida usando gauss_jordan():\n", A_gj)


Matriz A inicial:
 [[ 3. -2.  2.  1.]
 [ 1. -1. -1. -3.]
 [ 2.  1.  2.  4.]
 [ 4. -4.  1.  2.]]

Paso 1:
 [[ 1.         -0.66666667  0.66666667  0.33333333]
 [ 1.         -1.         -1.         -3.        ]
 [ 2.          1.          2.          4.        ]
 [ 4.         -4.          1.          2.        ]]

Paso 2:
 [[ 1.         -0.66666667  0.66666667  0.33333333]
 [ 0.         -0.33333333 -1.66666667 -3.33333333]
 [ 0.          2.33333333  0.66666667  3.33333333]
 [ 0.         -1.33333333 -1.66666667  0.66666667]]

Paso 3:
 [[ 1.         -0.66666667  0.66666667  0.33333333]
 [-0.          1.          5.         10.        ]
 [ 0.          2.33333333  0.66666667  3.33333333]
 [ 0.         -1.33333333 -1.66666667  0.66666667]]

Paso 4:
 [[  1.   0.   4.   7.]
 [ -0.   1.   5.  10.]
 [  0.   0. -11. -20.]
 [  0.   0.   5.  14.]]

Paso 5:
 [[ 1.          0.          4.          7.        ]
 [-0.          1.          5.         10.        ]
 [-0.         -0.          1.          1.818

7. Encuentra la inversa de la matriz del ejercicio 1.

In [11]:
import numpy as np

A = np.array([
    [3, -2, 2, 1],
    [1, -1, -1, -3],
    [2, 1, 2, 4],
    [4, -4, 1, 2]
], dtype=float)


I = np.eye(A.shape[0])

AI = np.hstack((A, I))

def gauss_jordan_elimination(AI):

    m, n = AI.shape
    for i in range(m):

        AI[i] = AI[i] / AI[i, i]

        for j in range(m):
            if i != j:
                AI[j] = AI[j] - AI[i] * AI[j, i]
    return AI

AI_gj = gauss_jordan_elimination(AI.copy())

A_inv = AI_gj[:, A.shape[1]:]

print("Matriz inversa de A:\n", A_inv)


Matriz inversa de A:
 [[-0.16666667  0.5         0.38888889  0.05555556]
 [-0.11111111  0.33333333  0.37037037 -0.18518519]
 [ 0.77777778 -0.33333333 -0.25925926 -0.37037037]
 [-0.27777778 -0.16666667  0.09259259  0.2037037 ]]


8. Resuelva el siguiente sistema de ecuaciones:

$$ \begin{array}{ccc}5x&+7y&-z&=6\\2x&+10y&-2z&=4\\x&+y&+z&=0\\ \end{array} $$

In [15]:
import numpy as np

# Coeficientes de las ecuaciones
A = np.array([[5, 7, -1],
              [2, 10, -2],
              [1, 1, 1]])

# Términos independientes
b = np.array([6, 4, 0])

# Resolvemos el sistema de ecuaciones
solucion = np.linalg.solve(A, b)

print(f"La solución del sistema es: x = {solucion[0]}, y = {solucion[1]}, z = {solucion[2]}")


La solución del sistema es: x = 1.0000000000000002, y = -1.2335811384723962e-16, z = -1.0000000000000002
