<a href="https://colab.research.google.com/github/AndresMendoza30/repositorio1/blob/EJERCICIOS-PARA-EL-1-DE-ABRIL/Tarea4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Primer ejercicio



Cree la matriz
$${A}=\begin{bmatrix}1&0&0&0\\2&0&0&0\\0&3&3&0\\0&3&4&1\\0&1&2&1\end{bmatrix}$$



In [1]:
import numpy as np

# Definir la matriz A
A = np.array([[1, 0, 0, 0],
              [2, 0, 0, 0],
              [0, 3, 3, 0],
              [0, 3, 4, 1],
              [0, 1, 2, 1]])

# Mostrar la matriz A
print("Matriz A:")
print(A)


Matriz A:
[[1 0 0 0]
 [2 0 0 0]
 [0 3 3 0]
 [0 3 4 1]
 [0 1 2 1]]


Cree a partir de ${A}$ una matriz cuya única columna sea la
primera columna de ${A}$



In [3]:
# Definir la matriz A
A = np.array([[1, 0, 0, 0],
              [2, 0, 0, 0],
              [0, 3, 3, 0],
              [0, 3, 4, 1],
              [0, 1, 2, 1]])

# Seleccionar la primera columna de A
primera_columna = A[:, 0]

# Crear una nueva matriz con la única columna de A
nueva_matriz = primera_columna.reshape(-1, 1)

# Mostrar la nueva matriz
print("Matriz con única columna de A:")
print(nueva_matriz)


Matriz con única columna de A:
[[1]
 [2]
 [0]
 [0]
 [0]]


Cree a partir de ${A}$ una matriz cuya única columna sea la segunda
fila de ${A}$



In [4]:
# Definir la matriz A
A = np.array([[1, 0, 0, 0],
              [2, 0, 0, 0],
              [0, 3, 3, 0],
              [0, 3, 4, 1],
              [0, 1, 2, 1]])

# Seleccionar la segunda fila de A y convertirla en una matriz columna
segunda_fila = A[1, :].reshape(-1, 1)

# Mostrar la nueva matriz
print("Matriz con única columna de la segunda fila de A:")
print(segunda_fila)


Matriz con única columna de la segunda fila de A:
[[2]
 [0]
 [0]
 [0]]


<div class="EXERCISE">
Cree a partir de $A$ una matriz cuya única fila sea la primera
fila de $A$

</div>



In [5]:
# Definir la matriz A
A = np.array([[1, 0, 0, 0],
              [2, 0, 0, 0],
              [0, 3, 3, 0],
              [0, 3, 4, 1],
              [0, 1, 2, 1]])

# Seleccionar la primera fila de A y convertirla en una matriz fila
primera_fila = A[0, :].reshape(1, -1)

# Mostrar la nueva matriz
print("Matriz con única fila de la primera fila de A:")
print(primera_fila)


Matriz con única fila de la primera fila de A:
[[1 0 0 0]]


### Segundo ejercicio



Calcule el siguiente vector: 3 veces la primera columna de $A$
menos la segunda columna de $A$ mas 2 veces la tercera columna
menos 3 veces la última columna de $A$



In [6]:
import numpy as np

# Definir la matriz A
A = np.array([[1, 0, 0, 0],
              [2, 0, 0, 0],
              [0, 3, 3, 0],
              [0, 3, 4, 1],
              [0, 1, 2, 1]])

# Calcular el vector resultante
vector_resultante = 3 * A[:, 0] - A[:, 1] + 2 * A[:, 2] - 3 * A[:, 3]

# Mostrar el vector resultante
print("Vector resultante:")
print(vector_resultante)


Vector resultante:
[3 6 3 2 0]


### Tercer ejercicio



Proporcione ejemplos de matrices 3 por 3 no nulas de los siguientes
tipos de matrices:

-   Una matriz diagonal



In [7]:

# Matriz diagonal
matriz_diagonal = np.diag([1, 2, 3])

print("Matriz diagonal:")
print(matriz_diagonal)


Matriz diagonal:
[[1 0 0]
 [0 2 0]
 [0 0 3]]


-   Una matriz simétrica



In [8]:

# Definir una matriz simétrica 3x3
matriz_simetrica = np.array([[1, 2, 3],
                             [2, 4, 5],
                             [3, 5, 6]])

print("Matriz simétrica:")
print(matriz_simetrica)


Matriz simétrica:
[[1 2 3]
 [2 4 5]
 [3 5 6]]


-   Una matriz triangular superior (es decir, que todos los elementos
    por *debajo* de la diagonal son nulos).



In [9]:

# Definir una matriz triangular superior 3x3
matriz_triangular_sup = np.array([[1, 2, 3],
                                  [0, 4, 5],
                                  [0, 0, 6]])

print("Matriz triangular superior:")
print(matriz_triangular_sup)


Matriz triangular superior:
[[1 2 3]
 [0 4 5]
 [0 0 6]]


-   Una matriz antisimétrica (es decir, que su transpuesta es igual a su opuesta: $ {A}^{T}=-A $ ).



In [10]:

# Definir una matriz antisimétrica 3x3
matriz_antisimetrica = np.array([[0, 1, -2],
                                 [-1, 0, 3],
                                 [2, -3, 0]])

# Comprobar si la matriz es antisimétrica
es_antisimetrica = np.allclose(matriz_antisimetrica, -matriz_antisimetrica.T)

print("Matriz antisimétrica:")
print(matriz_antisimetrica)

if es_antisimetrica:
    print("La matriz es antisimétrica.")
else:
    print("La matriz no es antisimétrica.")


Matriz antisimétrica:
[[ 0  1 -2]
 [-1  0  3]
 [ 2 -3  0]]
La matriz es antisimétrica.


### Cuarto ejercicio

# Propiedades del producto Matriz por vector

Genere una matriz $A$ (con el número de filas y columnas que
desee) y dos vectores ${b}$ y ${c}$ con tantos componentes
como columnas tenga $A$.

In [15]:
# Defina una matriz A
import numpy as np

# Definir las dimensiones de la matriz A
num_filas = 4
num_columnas = 3

# Generar una matriz A de dimensiones num_filas x num_columnas
A = np.random.randint(1, 10, size=(num_filas, num_columnas))

In [12]:
# Defina el vector b con tantos componentes como columnas tenga la matriz A
b = np.random.randint(1, 10, size=num_columnas)

In [14]:
# Defina el vector c con tantos componentes como el vector b
c = np.random.randint(1, 10, size=num_columnas)
# Mostrar la matriz A, los vectores b y c
print("Matriz A:")
print(A)

print("\nVector b:")
print(b)

print("\nVector c:")
print(c)

Matriz A:
[[1 0 0 0]
 [2 0 0 0]
 [0 3 3 0]
 [0 3 4 1]
 [0 1 2 1]]

Vector b:
[4 4 5]

Vector c:
[2 1 6]


Y ahora verifique las propiedades vistas en el curso (en todos los
casos, verifique sus ejemplos también con lapiz y papel... recuerde
que primero se realizan las operaciones encerradas entre paréntesis).

$$ A({b}+{c}) = A{b} + A{c} $$

In [16]:
# Definir la matriz A, los vectores b y c
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

b = np.array([2, 3, 4])
c = np.array([5, 6, 7])

In [17]:
# escriba aquí la parte izquierda de la ecuación: A*(b+c)
resultado_izquierda = A.dot(b + c)

In [19]:
# escriba aquí la parte derecha de la ecuación
resultado_derecha = A.dot(b) + A.dot(c)
if np.array_equal(resultado_izquierda, resultado_derecha):
    print("La propiedad A(b+c) = Ab + Ac se cumple.")
    print("Resultado izquierdo:", resultado_izquierda)
    print("Resultado derecho:", resultado_derecha)
else:
    print("La propiedad A(b+c) = Ab + Ac no se cumple.")
    print("Resultado izquierdo:", resultado_izquierda)
    print("Resultado derecho:", resultado_derecha)

La propiedad A(b+c) = Ab + Ac se cumple.
Resultado izquierdo: [ 58 139 220]
Resultado derecho: [ 58 139 220]


### Quinto ejercicio

Decida un valor para el escalar $\lambda$ y verifique que
$$ A(\lambda{b}) = \lambda(A{b})$$

In [38]:
import numpy as np

# Definir un valor para el escalar λ
lmbda = 2

# Definir la matriz A y el vector b
A = np.array([[1, 3],
              [9, 7]])
b = np.array([5, 10])

In [30]:
# escriba aquí la parte izquierda de la ecuación
izquierda = A.dot(lmbda * b)

In [39]:
# escriba aquí la parte derecha de la ecuación
derecha = lmbda * A.dot(b)

# Verificar si los resultados son iguales
if np.array_equal(izquierda, derecha):
    print("La propiedad A(λb) = λ(Ab) se cumple.")
    print("Resultado izquierdo:", izquierda)
    print("Resultado derecho:", derecha)
else:
    print("La propiedad A(λb) = λ(Ab) no se cumple.")
    print("Resultado izquierdo:", izquierda)
    print("Resultado derecho:", derecha)

La propiedad A(λb) = λ(Ab) no se cumple.
Resultado izquierdo: [34 78]
Resultado derecho: [ 70 230]


Compuebe que en este caso no son necesarios los paréntesis:
$$\lambda A{b}\;$$ (aunque en Python siempre necesite
escribir los símbolos de producto `*`). Pruebe a colocar el escalar en
cualquier posición, pero mantenga la matriz a la izquierda del vector.

In [34]:
import numpy as np

# Definir un valor para el escalar λ
lmbda = 2

# Definir la matriz A y el vector b
A = np.array([[1, 2],
              [3, 4]])
b = np.array([5, 6])

# Realizar la operación sin paréntesis adicionales
resultado_sin_parentesis = lmbda * A.dot(b)

# Realizar la operación con paréntesis para comparar
resultado_con_parentesis = (lmbda * A).dot(b)

# Verificar si los resultados son iguales
if np.array_equal(resultado_sin_parentesis, resultado_con_parentesis):
    print("En el caso λAb no son necesarios los paréntesis.")
    print("Resultado sin paréntesis:", resultado_sin_parentesis)
    print("Resultado con paréntesis:", resultado_con_parentesis)
else:
    print("En el caso λAb son necesarios los paréntesis.")
    print("Resultado sin paréntesis:", resultado_sin_parentesis)
    print("Resultado con paréntesis:", resultado_con_parentesis)


En el caso λAb no son necesarios los paréntesis.
Resultado sin paréntesis: [34 78]
Resultado con paréntesis: [34 78]


### Sexto ejercicio

Genere una matriz ${B}$ del mismo orden que $A$

In [40]:
import numpy as np

# Definir las dimensiones de la matriz B
num_filas = 3
num_columnas = 3

# Generar una matriz B del mismo orden que A con valores aleatorios
B = np.random.randint(1, 10, size=(num_filas, num_columnas))

# Mostrar la matriz B
print("Matriz B:")
print(B)


Matriz B:
[[9 2 9]
 [3 7 8]
 [6 3 5]]


Verifique que

$$ (A+B){c} = A{c} + B{c}$$

In [46]:
import numpy as np

# Definir la matriz A, la matriz B y el vector c
A = np.array([[1, 2, 3],
              [7, 10, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 7, 9],
              [3, 2, 1]])

c = np.array([2, 3, 4])

In [42]:
izquierda = (A + B).dot(c)

In [43]:
# escriba aquí la parte derecha de la ecuación
derecha = A.dot(c) + B.dot(c)

In [47]:
if np.array_equal(izquierda, derecha):
    print("La propiedad (A+B)c = Ac + Bc se cumple.")
    print("Resultado izquierdo:", izquierda)
    print("Resultado derecho:", derecha)
else:
    print("La propiedad (A+B)c = Ac + Bc no se cumple.")
    print("Resultado izquierdo:", izquierda)
    print("Resultado derecho:", derecha)

La propiedad (A+B)c = Ac + Bc se cumple.
Resultado izquierdo: [90 90 90]
Resultado derecho: [90 90 90]


In [45]:
# escriba aquí la parte izquierda de la ecuación (¿funciona sin paréntesis?)
# Definir la matriz A, la matriz B y el vector c
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

c = np.array([2, 3, 4])

# Calcular la parte izquierda de la ecuación sin paréntesis adicionales
parte_izquierda_sin_parentesis = (A + B).dot(c)

print("Parte izquierda de la ecuación sin paréntesis adicionales:")
print(parte_izquierda_sin_parentesis)


Parte izquierda de la ecuación sin paréntesis adicionales:
[90 90 90]


# Dos propiedades de la transposición

Recuerde que `~A` es la transpuesta de `A`.

Verfique que
$$
(A+B)^T=A^{T}+B^{T}
$$

In [48]:
import numpy as np

# Definir la matriz A y la matriz B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

In [49]:
# escriba aquí la parte izquierda de la ecuación: ~(A + B)
parte_izquierda = (A + B).T


In [51]:
# escriba aquí la parte derecha de la ecuación
parte_derecha = A.T + B.T
if np.array_equal(parte_izquierda, parte_derecha):
    print("La propiedad (A + B)^T = A^T + B^T se cumple.")
    print("Resultado izquierdo:", parte_izquierda)
    print("Resultado derecho:", parte_derecha)
else:
    print("La propiedad (A + B)^T = A^T + B^T no se cumple.")
    print("Resultado izquierdo:", parte_izquierda)
    print("Resultado derecho:", parte_derecha)

La propiedad (A + B)^T = A^T + B^T se cumple.
Resultado izquierdo: [[10 10 10]
 [10 10 10]
 [10 10 10]]
Resultado derecho: [[10 10 10]
 [10 10 10]
 [10 10 10]]


¿Necesitamos usar paréntesis para el lado izquierdo? ¿Y para el derecho?

In [52]:
# Definir la matriz A y la matriz B
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

# Calcular la parte izquierda de la ecuación sin paréntesis adicionales
parte_izquierda_sin_parentesis = (A + B).T

# Calcular la parte derecha de la ecuación sin paréntesis adicionales
parte_derecha_sin_parentesis = A.T + B.T

# Verificar si los resultados son iguales
if np.array_equal(parte_izquierda_sin_parentesis, parte_derecha_sin_parentesis):
    print("No son necesarios paréntesis adicionales para ambos lados de la ecuación.")
    print("Resultado izquierdo:", parte_izquierda_sin_parentesis)
    print("Resultado derecho:", parte_derecha_sin_parentesis)
else:
    print("Los paréntesis adicionales son necesarios para al menos uno de los lados de la ecuación.")
    print("Resultado izquierdo:", parte_izquierda_sin_parentesis)
    print("Resultado derecho:", parte_derecha_sin_parentesis)


No son necesarios paréntesis adicionales para ambos lados de la ecuación.
Resultado izquierdo: [[10 10 10]
 [10 10 10]
 [10 10 10]]
Resultado derecho: [[10 10 10]
 [10 10 10]
 [10 10 10]]


Decida un valor para $\lambda$ y verfique que
$$
(\lambda A)^T=\lambda(A^{T})
$$

In [54]:
# Definir un valor para el escalar λ
lmbda = 2

# Definir la matriz A
A = np.array([[1, 2],
              [3, 4]])

In [56]:
# escriba aquí la parte izquierda de la ecuación:
lado_izquierdo = (lmbda * A).T


In [55]:
# escriba aquí la parte derecha de la ecuación
lado_derecho = lmbda * A.T
if np.array_equal(lado_izquierdo, lado_derecho):
    print("La propiedad (λA)^T = λ(A^T) se cumple.")
    print("Resultado izquierdo:", lado_izquierdo)
    print("Resultado derecho:", lado_derecho)
else:
    print("La propiedad (λA)^T = λ(A^T) no se cumple.")
    print("Resultado izquierdo:", lado_izquierdo)
    print("Resultado derecho:", lado_derecho)

La propiedad (λA)^T = λ(A^T) no se cumple.
Resultado izquierdo: [[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
Resultado derecho: [[2 6]
 [4 8]]
